In [1]:
import numpy as np

In [8]:
# a simply array
a1 = np.array([1,2,3,4,5])
a1


array([1, 2, 3, 4, 5])

In [9]:
list = [2,3,5,6,8]
newArray = np.array(list)
newArray
#print(type(newArray))

array([2, 3, 5, 6, 8])

TypeError: Tuple must have size 2, but has size 5

In [17]:
print(a1)
print(type(a1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [18]:
np.size(a1)

5

In [22]:
a2 = np.array([1,2,3,4,"ashwin",6.4])
a2
a2.dtype

dtype('<U32')

In [24]:
a10 = np.array([1,2,3,4,9.9,6.4])
a10
a10.dtype

dtype('float64')

In [25]:
print(np.size(a2))
print("------")
print(type(a2))
print("-----")
print(a2.dtype)

6
------
<class 'numpy.ndarray'>
-----
<U32


In [30]:
a3 = np.array([2]*10)
print(a3)
print("------")
print(np.size(a3))
print("----")
a3.dtype

[2 2 2 2 2 2 2 2 2 2]
------
10
----


dtype('int64')

In [31]:
a4 = np.array(range(10))
print(a4)
print("----")
np.size(a4)
print("----")
a4.dtype

[0 1 2 3 4 5 6 7 8 9]
----
----


dtype('int64')

In [32]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
tenten = np.array([10] * 10, dtype = int)
print(tenten)
print(np.size(tenten))
print(type(tenten))
print(tenten.dtype)

[10 10 10 10 10 10 10 10 10 10]
10
<class 'numpy.ndarray'>
int64


In [33]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [44]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [45]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
np.arange(10, 20, 2, dtype = float)

array([10., 12., 14., 16., 18.])

In [52]:
x = np.arange(20, 100, 10 , dtype = int)
print(x)
y = np.arange(20,100,10, dtype = float)
print(y)

[20 30 40 50 60 70 80 90]
[20. 30. 40. 50. 60. 70. 80. 90.]


In [17]:
np.arange(20, 100, 10)

array([20, 30, 40, 50, 60, 70, 80, 90])

In [18]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [53]:
xDec = np.arange(10, 0, -1)
print(xDec)
yDec = np.arange(10, 0, -1, dtype = float)
yDec

[10  9  8  7  6  5  4  3  2  1]


array([10.,  9.,  8.,  7.,  6.,  5.,  4.,  3.,  2.,  1.])

In [20]:
np.linspace(5, 10, 11)

array([ 5. ,  5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [54]:
np.linspace(1, 100, 5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [57]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [58]:
np.linspace(0, 100, 4)

array([  0.        ,  33.33333333,  66.66666667, 100.        ])

In [59]:
a = np.arange(0, 10)
a1 = a * 2
a1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [60]:
a2 = np.arange(10, 20)
a2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [61]:
a1 + a2

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37])

In [74]:
m = np.array([[1,3,4], [5,4,9.9]])
print(m)
print(type(m))
print(m.dtype)
print(np.size(m, 0))
print(np.size(m, 1))

[[1.  3.  4. ]
 [5.  4.  9.9]]
<class 'numpy.ndarray'>
float64
2
3


In [75]:
m = np.arange(0, 20).reshape(5, 4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [76]:
np.size(m)

20

In [77]:
np.size(m, 0)

5

In [78]:
np.size(m, 1)

4

In [79]:
m[1,2]

6

In [80]:
m[0,0]

0

In [81]:
m[0,1]

1

In [82]:
m[0,2]

2

In [83]:
m[1,0]

4

In [84]:
m[2,0]

8

In [85]:
m[2,]

array([ 8,  9, 10, 11])

In [86]:
m[:,2]

array([ 2,  6, 10, 14, 18])

In [87]:
a = np.arange(5)
print(a)

[0 1 2 3 4]


In [88]:
print(a < 2)
print(a > 2)
print(a)
(a < 2) |(a > 3)

[ True  True False False False]
[False False False  True  True]
[0 1 2 3 4]


array([ True,  True, False, False,  True])

In [48]:
def exp(x):
    return x<3 or x>3


In [93]:
lista = np.array((1,3,2,4,3,7,4,5,7,8,7,9,6,2,4,5))
def exp(y):
    return y<5
exp(lista)

array([ True,  True,  True,  True,  True, False,  True, False, False,
       False, False, False, False,  True,  True, False])

In [94]:
print(exp(4))
print(exp(3))
print(exp(2))
print(exp(5))

True
True
True
False


In [120]:
x = np.arange(1, 100)
y = np.array(x)
print(y)
print("ten", np.sum(y<10))
print(np.sum(x<3))
np.sum(x < 20)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]
ten 9
2


19

In [108]:
z = np.arange(0, 10)
print(z)
np.vectorize(exp)(z)

[0 1 2 3 4 5 6 7 8 9]


array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [125]:
a = np.array([1,3,4,5,6,75,4,4])
print(a)
r = a < 6
print(r)

print(a[r])

[ 1  3  4  5  6 75  4  4]
[ True  True  True  True False False  True  True]
[1 3 4 5 4 4]


In [126]:
print(a)
np.sum(a)

[ 1  3  4  5  6 75  4  4]


102

In [127]:
print(np.sum(r))

6


In [129]:
print(np.sum(a<5))

5


In [68]:
a1 = np.arange(0,5)
print(a1)
a2 = np.arange(5,0,-1)
print(a2)

[0 1 2 3 4]
[5 4 3 2 1]


In [130]:
a1 < a2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [131]:
a1 = np.arange(9).reshape(3,3)
print(a1)
print(a1.shape)
a2 = np.arange(9,0,-1).reshape(3,3)
print(a2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(3, 3)
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [132]:
a1  == a2

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [133]:
a1 < a2

array([[ True,  True,  True],
       [ True,  True, False],
       [False, False, False]])

In [134]:
a1 = np.arange(1,10)
print(a1)
print(a1[3:8])
print(a1[:5])
print(a1[2:])
print(a1[::2])
print(a1[:])

[1 2 3 4 5 6 7 8 9]
[4 5 6 7 8]
[1 2 3 4 5]
[3 4 5 6 7 8 9]
[1 3 5 7 9]
[1 2 3 4 5 6 7 8 9]


In [135]:
print(a1[::-1])
print(a1[-1:-5:-1])
print(a1[5:1:-1])

[9 8 7 6 5 4 3 2 1]
[9 8 7 6]
[6 5 4 3]


In [136]:
print(m)
m[:,1]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


array([ 1,  5,  9, 13, 17])

In [137]:
m[: ,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18]])

In [138]:
m[3:10, 1:3]

array([[13, 14],
       [17, 18]])

In [139]:
m[[1,3,4],:]

array([[ 4,  5,  6,  7],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [140]:
a = np.arange(0, 9)
print(a)
m = a.reshape(3,3)
m

[0 1 2 3 4 5 6 7 8]


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [141]:
reshaped = m.reshape(9)
reshaped
reshaped.shape

(9,)

In [142]:
m.shape

(3, 3)

In [112]:
raveled = m.ravel()
raveled

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [113]:
raveled.shape


(9,)

In [114]:
#PAGE 68

In [148]:
#transpose a matrix
m2 = np.arange(0,9).reshape(3,3)
flattened = m2.flatten()
flattened

array([0, 1, 2, 3, 4, 5, 6, 7, 8])