In [3]:
import numpy as np
import pandas as pd
pd.set_option('display.notebook_repr_html', False)
pd.set_option('display.max_columns', 10)
pd.set_option('display.max_rows',10)

In [24]:
s1 = pd.Series(2)
print(s1)
print(s1[0])
print(type(s1))
s1.dtype

0    2
dtype: int64
2
<class 'pandas.core.series.Series'>


dtype('int64')

In [26]:
s2 = pd.Series([1,2,3,4,5])
s2

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [27]:
s2.values

array([1, 2, 3, 4, 5])

In [28]:
s2.index

RangeIndex(start=0, stop=5, step=1)

In [37]:
s3 = pd.Series([1,2,3], index=["a","b","c"])
print(s3)
s3.index


a    1
b    2
c    3
dtype: int64


Index(['a', 'b', 'c'], dtype='object')

In [32]:
print(s3[0])
print(s3[1])
print(s3[2])

1
2
3


In [40]:
print(s3["a"])
print(s3["b"])
print(s3["c"])

1
2
3


In [43]:
s4 = pd.Series(2, index=s2.index)
s4

0    2
1    2
2    2
3    2
4    2
dtype: int64

In [44]:
s5 = pd.Series(4, index = s3.index)
s5

a    4
b    4
c    4
dtype: int64

In [58]:
#generate a series from 5 normal random numbers
np.random.seed(123456)
pd.Series(np.random.randn(5))

0   -0.673690
1    0.113648
2   -1.478427
3    0.524988
4    0.404705
dtype: float64

In [59]:
pd.Series(np.linspace(0,9,10))

0    0.0
1    1.0
2    2.0
3    3.0
4    4.0
5    5.0
6    6.0
7    7.0
8    8.0
9    9.0
dtype: float64

In [60]:
pd.Series(np.arange(0,9))

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
dtype: int64

In [62]:
# create Series from dict
pd.Series({'a': 1, "b": 5, "c": 7})

a    1
b    5
c    7
dtype: int64

In [65]:
 # example series, which also contains a NaN
s = pd.Series([0,1,1,2,3,4,5,6,7,np.nan])
s

0    0.0
1    1.0
2    1.0
3    2.0
4    3.0
5    4.0
6    5.0
7    6.0
8    7.0
9    NaN
dtype: float64

In [76]:
 # size is also the # of items in the Series
# length of the Series #len(s) 
print(s.size)
print(len(s))

10
10


In [75]:
# .shape is a tuple with one value
s.shape

(10,)

In [69]:
#count returns the number of non-NAN values
s.count()

9

In [73]:
# all unique values
s.unique()

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7., nan])

In [74]:
# count of non-NaN values, returned max to min order
s.value_counts()

1.0    2
0.0    1
2.0    1
3.0    1
4.0    1
5.0    1
6.0    1
7.0    1
dtype: int64

In [77]:
  # first five
s.head()

0    0.0
1    1.0
2    1.0
3    2.0
4    3.0
dtype: float64

In [78]:
#first 10
s.head(10)

0    0.0
1    1.0
2    1.0
3    2.0
4    3.0
5    4.0
6    5.0
7    6.0
8    7.0
9    NaN
dtype: float64

In [79]:
s.head(n=3)

0    0.0
1    1.0
2    1.0
dtype: float64

In [81]:
s.tail()

5    4.0
6    5.0
7    6.0
8    7.0
9    NaN
dtype: float64

In [82]:
s.tail(n=3)

7    6.0
8    7.0
9    NaN
dtype: float64

In [84]:
# only take specific items
s.take([0,3,9])

0    0.0
3    2.0
9    NaN
dtype: float64

In [87]:
 # single item lookup
s3 = pd.Series([1,2,3], index=["a","b","c"])
s3['a']

1

In [88]:
# lookup by position since the index is not an integer
s3[1]

2

In [89]:
s3[1] == s3["b"]

True

In [93]:
# multiple items
s3[['a','b','c']]


a    1
b    2
c    3
dtype: int64

In [95]:
s10 = pd.Series([1,2,3], index=[10,11,12])
s10

10    1
11    2
12    3
dtype: int64

In [99]:
s10[[10,11]]

10    1
11    2
dtype: int64

In [100]:
s10[11]

2

In [101]:
  # force lookup by index label
s10.loc[11]

2

In [105]:
# multiple items by label (loc)
s10.loc[[11,12]]

11    2
12    3
dtype: int64

In [104]:
# forced lookup by location / position
print(s10.iloc[0])
print(s10.iloc[1])
print(s10.iloc[2])

1
2
3


In [106]:
# multiple items by location / position (iloc)
s10.iloc[[0,2]]

10    1
12    3
dtype: int64

In [107]:
s10.ix[1,2]

AttributeError: 'Series' object has no attribute 'ix'

In [108]:
s6 = pd.Series([1,2,3,4], index = ['a','b','c','d'])
s6

a    1
b    2
c    3
d    4
dtype: int64

In [109]:
s7 = pd.Series([4,3,2,1], index = ['d','c','b','a'])
s7

d    4
c    3
b    2
a    1
dtype: int64

In [110]:
s6 + s7

a    2
b    4
c    6
d    8
dtype: int64

In [111]:
#just checking how the array adding works
x1 = np.array([1,2,3,4])
x2 = np.array([4,3,2,1])
x1 + x2

array([5, 5, 5, 5])

In [112]:
s6 * 3

a     3
b     6
c     9
d    12
dtype: int64

In [120]:
t = pd.Series(2, s3.index)
t

a    2
b    2
c    2
dtype: int64

In [123]:
s6 * t

a    2.0
b    4.0
c    6.0
d    NaN
dtype: float64

In [124]:
s6

a    1
b    2
c    3
d    4
dtype: int64

In [126]:
s8 = pd.Series({'a':1, 'b': 2, 'c': 3, 'd' : 5})
s8

a    1
b    2
c    3
d    5
dtype: int64

In [130]:
s9 = pd.Series({'b': 6, 'c': 7, 'd': 9, 'e': 10})
s9

b     6
c     7
d     9
e    10
dtype: int64

In [131]:
s8 + s9
(8, 10, 14)

(8, 10, 14)

In [136]:
s10 = pd.Series([1.0,2.0,3.0], index = ['a','a','b'])
s10

a    1.0
a    2.0
b    3.0
dtype: float64

In [137]:
s11 = pd.Series([4.0,5.0,6.0], index = ['a', 'a', 'c'])
s11

a    4.0
a    5.0
c    6.0
dtype: float64

In [138]:
s10 + s11

a    5.0
a    6.0
a    6.0
a    7.0
b    NaN
c    NaN
dtype: float64

In [140]:
#mean of numpy array values
nda = np.array([1,2,3,4,5])
nda.mean()

3.0

In [155]:
#mean of numpy array values with NaN

nda6 = np.array([1,2,3,4,5, np.NaN])
print(nda)
nda.mean()

[ 1.  2.  3.  4.  5. nan]


nan

In [157]:
s = pd.Series(nda6)
print(s)
print(s.count())
print(s.mean())

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
5    NaN
dtype: float64
5
3.0


In [170]:
e = pd.Series(np.arange(0,10))
e
#print(e > 5)
result = (e > 5)
e[result]

6    6
7    7
8    8
9    9
dtype: int64

In [ ]:
# commented as it throws an exception/error
e[e > 5 and e < 8]

In [173]:
 # correct syntax
e[(e>4) & (e<8)]

5    5
6    6
7    7
dtype: int64

In [177]:
## are all items >= 0?
(e>0).all()

False

In [178]:
# any items < 2?
(e<2).any()

True

In [179]:
# how many values < 2?
(e<2).sum()

2

In [181]:
# sample series of five items
i = pd.Series(np.random.randn(5))
i

0   -1.344312
1    0.844885
2    1.075770
3   -0.109050
4    1.643563
dtype: float64

In [183]:
#change the index
i.index = ['a','b','c','d','e']
i

a   -1.344312
b    0.844885
c    1.075770
d   -0.109050
e    1.643563
dtype: float64

In [184]:
# concat copies index values verbatim,
   # potentially making duplicates
np.random.seed(123456)
s1 = pd.Series(np.random.randn(3))
s2 = pd.Series(np.random.randn(3))
combined = pd.concat([s1,s2])
combined

0    0.469112
1   -0.282863
2   -1.509059
0   -1.135632
1    1.212112
2   -0.173215
dtype: float64

In [185]:
#reset the index
combined.index = np.arange(0, len(combined))
combined.index

Int64Index([0, 1, 2, 3, 4, 5], dtype='int64')

In [186]:
combined

0    0.469112
1   -0.282863
2   -1.509059
3   -1.135632
4    1.212112
5   -0.173215
dtype: float64

In [190]:
np.random.seed(123456)
s1 = pd.Series(np.random.randn(4), index = ['a','b','c','d'])
s1

a    0.469112
b   -0.282863
c   -1.509059
d   -1.135632
dtype: float64

In [192]:
s2 = s1.reindex(['a','c','g'])
s2

a    0.469112
c   -1.509059
g         NaN
dtype: float64

In [193]:
s2['a'] = 0
s2

a    0.000000
c   -1.509059
g         NaN
dtype: float64